packages:
  - apps/*

allowBuilds:
  '@prisma/client': true
  '@prisma/engines': true
  bcrypt: true
  esbuild: true
  prisma: true
  protobufjs: true
  sharp: true
minimumReleaseAgeExclude:
  - resend@6.25.0
onlyBuiltDependencies:
  - '@prisma/client'
  - '@prisma/engines'
  - bcrypt
  - esbuild
  - prisma
  - protobufjs
  - sharp
